# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: herscat
version: 2

before:
  hooks:
    - rustup default stable

builds:
  - id: herscat-macos-arm64
    builder: rust
    binary: herscat
    command: cargo
    targets:
      - aarch64-apple-darwin
    flags: [--release]
    env: [RUSTFLAGS=-C target-cpu=native]

archives:
  - id: default
    builds:
      - herscat-macos-arm64
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Target }}"
    files:
      - LICENSE*
      - README*

checksum:
  name_template: "checksums_{{ .ProjectName }}_{{ .Version }}.txt"

release:
  draft: false
  prerelease: auto
  mode: append
