# Configure cross toolchain containers

[target.aarch64-unknown-linux-gnu]
# Ensure OpenSSL and pkg-config are available in the build container
pre-build = [
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config libssl-dev"
]
