# Configure cross toolchain containers

[target.aarch64-unknown-linux-gnu]
# Ensure OpenSSL and pkg-config are available in the build container
pre-build = [
  "dpkg --add-architecture arm64",
  "apt-get update",
  "apt-get install -y --no-install-recommends pkg-config pkg-config-aarch64-linux-gnu zlib1g-dev:arm64 libssl-dev:arm64 libssl-dev"
]

# Help openssl-sys find target headers and libs
[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG = "aarch64-linux-gnu-pkg-config"
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig/"
PKG_CONFIG_LIBDIR = "/usr/lib/aarch64-linux-gnu/pkgconfig"
OPENSSL_INCLUDE_DIR = "/usr/include/aarch64-linux-gnu"
OPENSSL_LIB_DIR = "/usr/lib/aarch64-linux-gnu"
TARGET_PKG_CONFIG = "aarch64-linux-gnu-pkg-config"
CC_aarch64_unknown_linux_gnu = "aarch64-linux-gnu-gcc"
CFLAGS_aarch64_unknown_linux_gnu = "-I/usr/include/aarch64-linux-gnu"
